### ISSUE TITLE
Deprecation warning with moment.js 2.10.6

### ISSUE THREAD

**Issue by CorasWorksSolutions** [c-trimm/moment-recur#42] opened 2015-10-01 17:21 UTC
Using moment.js 2.10.6, deprecation messages are displayed using an example from the README.md. Specifically:

recurrence = moment("2014/01/01").recur().every(2).days();

Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Error
    at Function.createFromInputFallback (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.js:746:36)
    at configFromString (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.js:826:32)
    at configFromInput (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.js:1353:13)
    at prepareConfig (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.js:1340:13)
    at createFromConfig (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.js:1307:44)
    at createLocalOrUTC (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.js:1385:16)
    at local__createLocal (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.js:1389:16)
    at utils_hooks__hooks (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.js:16:29)
    at eval (eval at evaluate (unknown source), <anonymous>:1:14)
    at Object.InjectedScript._evaluateOn (<anonymous>:904:55)

**Comment by ruler88** [comment] 2016-01-25 03:45
Same issue, I'm using moment.js 2.11.1

**Comment by ehdi** [comment] 2016-03-08 17:02
Please fix it

**Comment by bramski** [comment] 2016-03-08 17:30
Write a PR.  One of the contributors (such as myself) will merge it.

**Comment by dotnetchris** [comment] 2016-07-07 18:52
I really think this error message should handle a person using the US data format of MM/DD/YYYY and hint "please use YYYY-MM-DD". It took way too long for me to read 1407 and figure out why in the world i got that message for `moment("07/07/2016")`

**Comment by charleskhenry** [comment] 2016-08-21 15:45
Im still getting the same issue?

**Comment by gavin-hay** [comment] 2016-09-07 16:29
The issue is on line 743 in moment-recur.js as an internal re-constructor (if you will). The existing line reformats the date to YYYY/MM/DD - but it requires YYYY-MM-DD. Changing that line appropriately results in no warning being generated. I think is fixed in a recent PR.

**Comment by davidfloegel** [comment] 2016-09-16 16:54
Is the open PR for this issue getting merged any time soon? :) @bramski

**Comment by c-trimm** [comment] 2016-10-18 14:00
As of now, there are no instances of the format function being called using a deprecated format. It's not the job of moment-recur to let you know that you're using a deprecated date format, as moment already does that. Closing this.

**Closed by c-trimm** 2016-10-18 14:00 UTC
Labels: bug

**Comment by workdoer** [comment] 2017-02-12 14:09
Hi. In node js 

var moment = require('moment-timezone');
require('moment-recur');

on line 

moment().recur().every(1).dayOfMonth();

I have error

Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: 2017/02/12, _f: undefined, _strict: undefined, _locale: [object Object]

Why it's happened? 

If I have 
var moment = require('moment-timezone');

I have no such error. In package.json I have

    "moment": "^2.17.1",
    "moment-recur": "^1.0.5",
    "moment-timezone": "^0.5.11",

I use loopback js as framework.
